### ISSUE TITLE
l4d2_doorlock插件的小问题

### ISSUE THREAD

**Issue by shinubee** [umlka/l4d2#4]
我服务器上安装了门锁插件打三方图的时候，经常第一次加载是有倒计时的，团灭后第二轮的计时就没有了，希望可以修复一下。
另外我看到[agressive_specials_patch](https://github.com/umlka/l4d2/tree/main/agressive_specials_patch)，我安装的SourceScramble版本是0.7.0，还需要安装sourcescramble_manager.smx吗。

**Comment by umlka** [comment]
门锁问题无法重现
agressive_specials_patch是强制特感主动攻击的补丁(攻击性更强，只适用于LINUX)
只有SourceScramble配置的话需要安装sourcescramble_manager.smx
