### ISSUE TITLE
versus_coop_mode 签名可能需要更新

### ISSUE THREAD

**Issue by fantasylidong** [umlka/l4d2#6]
发现游戏更新后，一张图需要完成2次才能过关，应该是强行过关的签名失效了？
麻烦测试更新一下~

**Comment by umlka** [comment]
我找好签名后发你，现在没开服了

**Comment by umlka** [comment]
> 发现游戏更新后，一张图需要完成2次才能过关，应该是强行过关的签名失效了？ 麻烦测试更新一下~

有没有相关的报错

**Comment by umlka** [comment]
> 发现游戏更新后，一张图需要完成2次才能过关，应该是强行过关的签名失效了？ 麻烦测试更新一下~

你先把m_bIsFirstRoundFinished和m_bIsSecondRoundFinished的数值各加上192测试看看

**Comment by fantasylidong** [comment]
> > 发现游戏更新后，一张图需要完成2次才能过关，应该是强行过关的签名失效了？ 麻烦测试更新一下~
> 
> 有没有相关的报错

没有报错，+192我等会试一下，稍等

**Comment by fantasylidong** [comment]
> > 发现游戏更新后，一张图需要完成2次才能过关，应该是强行过关的签名失效了？ 麻烦测试更新一下~
> 
> 你先把m_bIsFirstRoundFinished和m_bIsSecondRoundFinished的数值各加上192测试看看

可以了，谢谢
