### ISSUE TITLE
关于一点map_changer的小问题

### ISSUE THREAD

**Issue by OblivioMortis** [umlka/l4d2#9]
如果使用Anne云服的Anne.vpk这个切换模式的脚本再加上versus_coop_mode和map_changer插件时，会出现官图救援异常问题，具体表现为救援卡住（C7M3被击倒后无法自动切换下张地图），其他的官图救援结束后不是黑屏就是黑屏一会儿然后又从头开始，但如果把mapchanger_finale_change_type的值改为2或者1就可以正常切换地图，我个人猜测是获取对抗救援关结束时的这里出了点问题，游戏以为战役已经结束，但换图插件还认为是对抗会换边进行第二轮救援才不会继续下去，因为不懂插件所以排查了很久才找到这个可能的问题，不知道以后会不会更新

![PixPin_2024-04-25_08-37-33](https://github.com/umlka/l4d2/assets/79137449/86ba2f07-127e-426e-9225-37050053103e)

**Comment by umlka** [comment]
因为map_changer只支持战役
